### ISSUE TITLE
Compile failed 

### ISSUE THREAD

**Issue by micromachine** [srotya/marauder#1]
Fresh Ubuntu  Trusty box 

greg@puter:~/maruder/marauder$ java -version 
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

greg@puter:~/maruder/marauder$ mvn validate | grep SUCC
[INFO] marauder ........................................... SUCCESS [  0.004 s]
[INFO] Marauder Library Module ............................ SUCCESS [  0.001 s]
[INFO] Marauder Analytics Module .......................... SUCCESS [  0.001 s]
[INFO] MarauderGenericSinkModule .......................... SUCCESS [  0.000 s]
[INFO] MarauderGenericSources ............................. SUCCESS [  0.000 s]
[INFO] Marader Snort Source ............................... SUCCESS [  0.001 s]
[INFO] BUILD SUCCESS
greg@puter:~/maruder/marauder$ 

[INFO] 26 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] marauder ........................................... SUCCESS [  0.006 s]
[INFO] Marauder Library Module ............................ SUCCESS [  2.021 s]
[INFO] Marauder Analytics Module .......................... FAILURE [  2.214 s]
[INFO] MarauderGenericSinkModule .......................... SKIPPED
[INFO] MarauderGenericSources ............................. SKIPPED
[INFO] Marader Snort Source ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.596 s
[INFO] Finished at: 2016-04-08T07:23:26+02:00
[INFO] Final Memory: 14M/206M
[INFO] ---------------

[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/indexing/SecondaryIndexer.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/passive/MarauderPassiveJobScheduler.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/passive/indexing/SecondaryIndexMapper.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/network/MarauderDNSCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/MarauderDirectoryCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/MarauderCorrelationModule.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/event/MarauderEventAttributeCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/network/MarauderFingerCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/indexing/MarauderIndexable.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/active/MarauderActiveAnalyticsService.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/passive/indexing/SecondaryIndexMRJob.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/active/storm/MarauderStormTopologyBuilder.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/passive/MarauderPassiveMRJob.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/constants/MarauderCorrelationTypes.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/event/MarauderTimeWindowEventCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/asset/MarauderAssetCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/active/storm/bolts/correlation/DirectoryCorrelationFeed.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/network/MarauderUserDeviceCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/MarauderThreatFeedCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/correlation/network/MarauderWhoIsCorrelation.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/passive/MarauderPassiveJobConstants.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/indexing/SecondaryIndexConstants.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/passive/indexing/SecondaryIndexReducer.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/active/storm/bolts/MarauderFilterBolt.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/passive/MarauderPassiveJobException.java:[1,1] class, interface, or enum expected
[ERROR] /home/greg/maruder/marauder/MarauderAnalyticsModule/src/main/java/org/ambud/marauder/analytics/active/storm/MarauderStormBoltBuilder.java:[1,1] class, interface, or enum expected

**Comment by ambud** [comment]
Please ignore the analytics module since the code repository had some issue which I am still fixing.

You should still be able to use the sources (IDS, Snort and Library).

**Comment by ambud** [comment]
I have updated the base code and everything should compile now.

**Comment by ambud** [comment]
Please let me know if I can close it the issue.

**Comment by micromachine** [comment]
Now work like a charm, You can close this issue.

**Comment by ambud** [comment]
Great, the artifacts have been published to maven central, you should be able to search them by com.srotya.marauder in search.maven.org
