### ISSUE TITLE
Complete deployment scenario is needed. 

### ISSUE THREAD

**Issue by micromachine** [srotya/marauder#2]
Step by step mini howto is needed. Maybe docker or vargant be useful for this. 
I suggest steps  : 
a) install and configure agent,
b) install and configure aggregator,
c) install and configure maruder controller, 
d) install and configure maruder cluster, 

Maybe linux .deb or .rpm prackage helps more

**Comment by ambud** [comment]
Thank you @micromachine, I will be slowly adding deployment documentation and automation for the rest of the components.

**Comment by micromachine** [comment]
Okay, I will wait :D

**Comment by micromachine** [comment]
Whats new ?

**Comment by ambud** [comment]
Working on additional data sources

**Comment by micromachine** [comment]
Something new ?

**Comment by ambud** [comment]
Marauder sources are being merged with Apache Nifi to give direct access to a wider variety of security event log sources. https://nifi.apache.org
